// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://pqzjbvtkubgvaytofjop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_G3GxhiMtpaAPBKfdXb55pQ_204QXN2B";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);